### PR TITLE
BUG: Exclude tasks run via a job from health check.

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
# Exclude tasks run via a job from health check

* Tasks which are run via job wrapper never have steps so the queue health check doesn't work properly
* This solution will exclude such tasks from the health check leaving the task processing run once without interruption
* If such task will timeout or is interrupted by other means the health check will not process such task

## Related issues

https://github.com/symbiote/silverstripe-queuedjobs/issues/325

## Tests

Test are passing on my local. The broken tests seem to be an upstream error.

### CODE REVIEW

**Comment by chillu** [comment]
Yep that looks great, thanks for looking at that so quickly Mojmir! I've since fixed it by increasing the `worker_ttl`, and just preparing a docs update to point out this footgun.

**Comment by chillu** [comment]
Docs at https://github.com/symbiote/silverstripe-queuedjobs/pull/327

**Comment by chillu** [comment]
The build failures should be fixed by https://github.com/symbiote/silverstripe-queuedjobs/pull/323. Happy with this PR, but can't merge myself (no permissions).

**Review by Cheddam — APPROVED** [review]
Thanks @mfendeksilverstripe!

**Pull request merged**
