### PR TITLE
Converted to PSR-2

### PR DESCRIPTION
**Pull request by helpfulrobot**
Hello!

I'm helpful robot. I noticed there were some deviations from PSR-2 in your code. The core committer team recently decided to transition SilverStripe Framework and CMS to PSR-2, and the [supported module standard](http://www.silverstripe.org/software/addons/supported-modules-definition) recommends following PSR-2. I've gone ahead and converted files in `code` and `tests` to PSR-2. If this sounds like something you'd like to merge then go right ahead! Feel free to ask questions or make suggestions for how I can help you more. I've been programmed with a wide range of responses.

Have a nice day! [gzzzzrrrkt]

### CODE REVIEW

**Comment by tractorcow** [comment]
I won't merge this unless @nyeholt feels this is appropriate..

@spekulatius do you have a feeling on this as well?

**Comment by spekulatius** [comment]
Hello @tractorcow and @nyeholt 

I had a quick look it is alright. The only thing im not a big fan of is adding not required methods like the constructor here: https://github.com/silverstripe-australia/silverstripe-queuedjobs/pull/73/files#diff-33694b82aadfd43a75604a715373adceR11

spek

**Comment by tractorcow** [comment]
@spekulatius The constructor was already there, wasn't it? It was just formatted in accordance with the standard.

**Comment by tractorcow** [comment]
@helpfulrobot this needs yet another rebase sorry.

**Comment by spekulatius** [comment]
Oh, okay @tractorcow. I had a very quick look.

Generally the rebase because of the merge issues will continue for a while because will face the merge conflicts with everyones changes based on the "old" code style. Step by step changes are less painful for a project with on going work.

**Comment by tractorcow** [comment]
I'll try to merge this once it's rebased immediately then. :)

Once everyone is on the same page it'll be smoother.

**Pull request closed without merging**
