### PR TITLE
BUG: Broken job handling when setup() throws

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
Apply the https://github.com/symbiote/silverstripe-queuedjobs/pull/263 to `4`

### CODE REVIEW

**Comment by mfendeksilverstripe** [comment]
@Cheddam Could you please have a look at this one?

**Comment by Cheddam** [comment]
@mfendeksilverstripe I'm a little confused - you used PHP 7.1-compatible syntax in #263 to make the `$job` parameter nullable, but here you drop the typehint entirely?

**Comment by mfendeksilverstripe** [comment]
You're right @Cheddam , for some reason I thought that nullable type hint is only since PHP `7.2`. I updated the PR, please review.

**Comment by Cheddam** [comment]
Thanks for the quick turnaround! Regrettably, after further review, this constitutes a major change. It'd be fine if `$job` was only used internally in this method, but @dnsl48 noted that it changes the signature of the `updateJobDescriptorAndJobOnException` extension point, which could break downstream code. On that basis, I don't think we can bring this fix to the `4` branch, sorry Mojmir 😞

**Comment by mfendeksilverstripe** [comment]
Fair enough, thanks for your help anyway

**Pull request closed without merging**
