### PR TITLE
Remove depreciated syntax for string subscript

### PR DESCRIPTION
**Pull request by JoshuaCarter**
Confirmed ready to merge

### CODE REVIEW

**Review by nglasl — APPROVED** [review]

**Comment by nglasl** [comment]
Hmm, not sure why your builds are suddenly failing.

> ERROR [Warning]: mysqli::real_connect(): (HY000/2002): Connection refused

**Comment by nglasl** [comment]
Oh they're now targeting completely different things https://travis-ci.org/github/symbiote/silverstripe-queuedjobs/builds/691619688 vs https://travis-ci.org/github/symbiote/silverstripe-queuedjobs/builds/693668675. So it seems like your configs might need updating?

**Comment by JoshuaCarter** [comment]
@nglasl I've updated the travis config to the same as the 3.1 branch (+ php 7.4) and added a some Object->SS_Object magic that I hadn't got around to yet. Can you take another look please.

**Comment by nglasl** [comment]
Nice, looking good.

**Pull request merged**
