### PR TITLE
only log if theres something to log

### PR DESCRIPTION
**Pull request by andrewandante**
Prevents the spam of empty INFO messages on Jobs as they run

### CODE REVIEW

**Comment by micschk** [comment]
Fixes #357

**Review by emteknetnz — APPROVED** [review]
Good

**Comment by emteknetnz** [comment]
I've retarted this to 4.9 and will tag 4.9.1

**Comment by emteknetnz** [comment]
I've re-targeted this to 4.9 and have tagged [4.9.1](https://github.com/symbiote/silverstripe-queuedjobs/releases/tag/4.9.1)

**Pull request merged**
