### PR TITLE
Abandoned doorman module replacement.

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
# Abandoned doorman module replacement

* abandoned module imported and updated

Abandoned [Async doorman](https://github.com/asyncphp/doorman) replaced with [Doorman process manager](https://github.com/silverstripe-terraformers/doorman-process-manager) which is the same module but it under our control and we can maintain it.

## Related issues

https://github.com/symbiote/silverstripe-queuedjobs/issues/292

### CODE REVIEW

**Comment by dhensby** [comment]
I'm not sure SS should be taking on the responsibility of maintaining an abandoned repo.

@assertchris can be contacted, he used to work for SS, if there's some real need to do it but simply being unhappy that a class is marked `final` isn't really going to be solved by a responsive maintainer because it's a stylistic choice.

If doorman is abandoned we need to remove support for it in favour of something else.

**Comment by assertchris** [comment]
Hey folks,

I'm happy to review and accept changes to the original module. I don't personally use it, and I don't receive most automated messages from GH because it would be overwhelming. 

@mfendeksilverstripe sorry for not seeing the changes you suggested sooner (removing the final keyword). They look good to me and I have merged them in. If you'd like to suggest further changes, let's chat. Seems @assertchris gets through my filters, or message me on https://twitter.com/assertchris.

**Comment by mfendeksilverstripe** [comment]
@assertchris Thanks for help, much appreciated ;-)

**Comment by mfendeksilverstripe** [comment]
Closing this as the original module got updated

**Comment by assertchris** [comment]
For future reference: this lead to 3.1.0 of doorman.

**Pull request closed without merging**
